/**
 * Author:  Marshall
 * Created: 12 déc. 2018
 */

CREATE TABLE CUSTOMER (
	CUSTOMER_ID INTEGER NOT NULL,
	DISCOUNT_CODE CHAR(1) NOT NULL,
	ZIP VARCHAR(10) NOT NULL,
	NAME VARCHAR(30),
	ADDRESSLINE1 VARCHAR(30),
	ADDRESSLINE2 VARCHAR(30),
	CITY VARCHAR(25),
	STATE CHAR(2),
	PHONE CHAR(12),
	FAX CHAR(12),
	EMAIL VARCHAR(40),
	CREDIT_LIMIT INTEGER,
	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE DISCOUNT_CODE (
	DISCOUNT_CODE CHAR(1) NOT NULL,
	RATE DECIMAL(5,3) CONSTRAINT NonNegativeRate CHECK (RATE >= 0.0),
	PRIMARY KEY (DISCOUNT_CODE)
);

CREATE TABLE MANUFACTURER (
	MANUFACTURER_ID INTEGER NOT NULL,
	NAME VARCHAR(30),
	ADDRESSLINE1 VARCHAR(30),
	ADDRESSLINE2 VARCHAR(30),
	CITY VARCHAR(25),
	STATE CHAR(2),
	ZIP CHAR(10),
	PHONE VARCHAR(12),
	FAX VARCHAR(12),
	EMAIL VARCHAR(40),
	REP VARCHAR(30),
	PRIMARY KEY (MANUFACTURER_ID)
);

CREATE TABLE MICRO_MARKET (
	ZIP_CODE VARCHAR(10) NOT NULL,
	RADIUS DOUBLE,
	AREA_LENGTH DOUBLE,
	AREA_WIDTH DOUBLE,
	PRIMARY KEY (ZIP_CODE)
);

CREATE TABLE PRODUCT (
	PRODUCT_ID INTEGER NOT NULL,
	MANUFACTURER_ID INTEGER NOT NULL,
	PRODUCT_CODE CHAR(2) NOT NULL,
	PURCHASE_COST DECIMAL(12,2),
	QUANTITY_ON_HAND INTEGER,
	MARKUP DECIMAL(4,2),
	AVAILABLE VARCHAR(5),
	DESCRIPTION VARCHAR(50),
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PRODUCT_CODE (
	PROD_CODE CHAR(2) NOT NULL,
	DISCOUNT_CODE CHAR(1) NOT NULL,
	DESCRIPTION VARCHAR(10),
	PRIMARY KEY (PROD_CODE)
);

CREATE TABLE PURCHASE_ORDER (
	ORDER_NUM INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	QUANTITY SMALLINT,
	SHIPPING_COST DECIMAL(12,2),
	SALES_DATE DATE,
	SHIPPING_DATE DATE,
	FREIGHT_COMPANY VARCHAR(30),
	PRIMARY KEY (ORDER_NUM)
);

INSERT INTO CUSTOMER(CUSTOMER_ID, DISCOUNT_CODE, ZIP, NAME, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, PHONE, FAX, EMAIL, CREDIT_LIMIT) VALUES 
